#+TITLE: Music Theory Course for RMA
#+AUTHOR: Matt Hood

* Principles
- Guided self-discovery via interactivity
- Aural training is essential for understanding music theory.
- Avoid teaching common practise harmony. Focus instead on jazz and pop. In the latter case, investigate cyclic chord progressions as discussed by 12tone, Neely, etc.


* Tags used in this document :meta:
** :meta:
Pertaining to organisation of this document
** :proposal:
An idea that seems good, but may well have alternatives that are better
** :openquestion:
An assumption about which I feel unsure, and could use some input from others
** :activity:
A topic that could use some interactive demonstration
** :explanation:
A topic that will be explained to students.


* Ideas
** DONE Note picker that is able to illustrate the process of moving from continuous frequency space to discrete notes that work well together
**Why?** Sound is a wilderness of discordance and dissonance. The machinery of tuning, scales, chords is all about finding the 'good notes', the subset of dissonance that is consonance. This exercise gives the student an appreciation of the value of elementary music theory, by experiencing how bad things are without it. This will then be a source of motivation to continue learning.



** TODO Intervals: Assign an emotional adjective to each interval (or any aural object really) and use the rest of the presentation

Aural Interval objects could be placed inline with text, featuring
- Official term as text
- Student-prescribed adjective
- Student-prescribed colour
- Plays the sound, with a random root note for relative objects


** TODO For relative pitch: play a song in a random key - first through earphones, then everyone together - note that they can still recognise the song even though the notes are totally different.


* Homework
** A separate presentation that gives homework in between sessions. :proposal:

* Outline
** Where to put note names? Initially I was thinking at the beginning, but what if we ditched note names until later? It would really hammer home the relative pitch idea. Many people initally fail to fully appreciate that tonal music theory works the same in any key. :openquestion:

**Module 1:** Ear training 101

** "Where are the good notes?" Continuous to discrete frequency space :activity:
*** Note names?
** Relative pitch vs absolute
*** Songs in different keys are still recognisable. Why? :activity:
*** For the 99% of us without perfect pitch, one note is as good as another. :explanation:
** Tones and semitones
*** Tones and semitones are the building block of relative music theory :explanation:
*** Learn to recognise :activity:
*** Learn to recognise multiple in a row :activity:
** What can we build with tones and semitones?
*** Scales, using sequences of tones, semitones: 
**** Take a random sequence of 7 tones and semitones to get different scale :activity:
**** Give an example of the 'major' scale and the 'minor' scale. Emohasise that this is foreshadowing, rather than something they should fully understand, since the significance of these scales cannot be appreciated with the explanations given so far. :explanation:
*** Chords, by combining tones, semitones to create bigger musical distances:
**** Same as above: random sequence of 3 tone/semitone + tone/semitone combinations to build different chords :activity:
**** Give examples of 'major' and 'minor' chord. This one is a little less arcane, since they will have played major and minor chords. Potential confusion around the common naming (major, minor) so reassure that this will be explained later. :explanation:
*** Intervals, by combining an arbitrary number of tones/semitones:
**** The work for this one will be done in the next module, so just give a few examples :activity:
**** Since tone = semitone + semitone, note that it is easier to just use semitones when defining intervals. :explanation:


**Module 2: ** To intervals and beyond
** Intervals

** Chords, built from intervals

** Scales, built from intervals
All with respect to a root note. Is this better than tone-semitone? Obscures the relative minor/major relationship, but I think that might be a red herring.

!! Note the circular defintion. Scales are defined here in terms of intervals (minor 3rd, major 6th), but the intervals are named by the scale degree on which they are used
*** Major
*** Minor



